### ISSUE TITLE
HTTPS Problem

### ISSUE THREAD

**Issue by chmosama** [nico-martin/progressive-wordpress#15]
I have a website running on Cloudflare HTTPS but with the help of wordpress-https plugin to redirect all HTTP request to HTTPS but still, I am getting this error your plugin setting page.

> Your site has to be served over https to use progressive web app features.

And on the about->status, it's showing a red cross mark on the HTTPS option but the website is already running on HTTPS.

![screenshot_77](https://user-images.githubusercontent.com/7778119/36350224-93ceefa8-14b6-11e8-91aa-d064bea4776d.png)

**Comment by nico-martin** [comment]
Hi @chmosama

Inside the normal "WordPress Settings -> General", whats the value of the site URL? Is it http or https?
If it is http, could you change it to https?

Kind regards,
Nico

**Comment by chmosama** [comment]
thank you, the problem is solved now. :+1:
