### ISSUE TITLE
Push notifications broken?

### ISSUE THREAD

**Issue by yusufk** [nico-martin/progressive-wordpress#16]
Hi,

I can't get push notifications working. No button, no registered devices etc.

What am I missing?

Regards,
Y

**Comment by nico-martin** [comment]
Hi Yusuf

First of all, thanks for using Progressive WordPress.

Did you insert the Firebase credentials?
And is «Add notification button» checked?

On the About page you should be able to download the logfile. Could you download it and send it to mail@nicomartin.ch?

Kind regards,
Nico

**Comment by yusufk** [comment]
Hi,

Herewith the important bits of the log, hope it helps:

`{
  "generated": "2018-03-10 15:44 (UTC)",
  "site_url": "https:\/\/www.masjidurrahmah.org.za\/site",
  "home_url": "https:\/\/www.masjidurrahmah.org.za\/site",
  "wpversion": "4.9.4",
  "multisite": false,
  "phpversion": "7.0.27-1~dotdeb+8.1",
  "stats": {
    "manifest": true,
    "sw": true,
    "rootwritable": true,
    "https": true
  },
  "settings": {
    "firebase-serverkey": "mykey",
    "firebase-senderid": "myid",
    "installable-enabled": "1",
    "manifest-name": "Masjid-ur-Rahmah",
    "manifest-short-name": "Masjid-ur-Rahmah",
    "manifest-starturl": "\/site",
    "manifest-description": "Masjid-ur-Rahmah can be translated as Masjid of Mercy. In a life of a Muslim Masjid represents a spiritual centre for the community by hosting a number of activities \u2013 primarily the five daily salaah (prayers) and dissemination of Islamic education.",
    "manifest-icon": "1445",
    "manifest-display": "fullscreen",
    "manifest-orientation": "any",
    "manifest-theme-color": "#000000",
    "manifest-background-color": "#ffffff",
    "offline-enabled": "1",
    "offline-page": "3",
    "offline-content": "",
    "offline-indicator": "1",
    "offline-indicator-text": "you&#039;re currently offline",
    "offline-indicator-position": "bottom",
    "offline-indicator-color-text": "#ffffff",
    "offline-indicator-color-background": "#000000",
    "pwp-force-deregister-sw": "0",
    "push-failed-remove": "0",
    "push-badge": "1445",
    "notification-button": "1",
    "notification-button-icon-color": "#fff",
    "notification-button-bkg-color": "#333"
  },`
